//src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/layouts/ThemeProvider";
import SessionProviderWrapper from "@/components/layouts/SessionProviderWrapper";
import ReduxProvider from "@/components/layouts/ReduxProvider";
import { NextAuthSync } from "@/components/layouts/NextAuthSync";
import AuthInitializer from "@/components/layouts/AuthInitializer";
import { AuthModal } from "@/components/layouts/AuthModal";
import { Toaster } from "react-hot-toast";
import AuthErrorHandler from "@/components/layouts/AuthErrorHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SessionProviderWrapper>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <AuthErrorHandler />
              <Toaster position="top-center" />
              <NextAuthSync />
              <AuthInitializer>{children}</AuthInitializer>
              <AuthModal />
            </ThemeProvider>
          </SessionProviderWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
